CREATE TABLE Card(
    uid INTEGER PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    info VARCHAR(32) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL,
    lastupdate timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES User(uid)
) DEFAULT CHARSET=utf8;

